[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://loveamys.netlify.app"

# Environment variables should be set in the Netlify dashboard:
# - SENDGRID_API_KEY: Your SendGrid API key
# - TO_EMAIL: The email address to receive orders (defaults to loveamys.bakes@gmail.com)

# Handle static assets with proper caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle CSS files specifically
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Ensure all static assets are served
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true 