[build]
  command = "npm run build"
  publish = "out"

# Handle static assets with proper caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle CSS files specifically
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Ensure all static assets are served
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true 